CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name  VARCHAR(100) NOT NULL,
  email      VARCHAR(255) UNIQUE NOT NULL,
  password   VARCHAR(255) NOT NULL,
  is_member  BOOLEAN DEFAULT FALSE,
  is_admin   BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS messages (
  id         SERIAL PRIMARY KEY,
  title      VARCHAR(255) NOT NULL,
  text       TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  user_id    INTEGER REFERENCES users(id) ON DELETE CASCADE
);
